LoadModule rewrite_module modules/mod_rewrite.so

<Directory "/usr/local/apache2/htdocs/">
    AllowOverride All
    # Se stai utilizzando Apache < 2.4:
    # Order allow,deny
    # Allow from all

    # Se stai utilizzando Apache >= 2.4:
    Require all granted

    # Opzionale, a seconda delle tue esigenze:
    Options +FollowSymLinks +Indexes
</Directory>



